"""empty message

Revision ID: 2c2933fca291
Revises: f3430fc9e44b
Create Date: 2024-11-13 22:51:53.171488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c2933fca291'
down_revision = 'f3430fc9e44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_db',
    sa.Column('name', sa.String(length=64), nullable=False, comment='分类名'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_db',
    sa.Column('content', sa.Text(), nullable=False, comment='留言内容'),
    sa.Column('ip', sa.Integer(), nullable=False, comment='ip'),
    sa.Column('address', sa.String(length=64), nullable=False, comment='地址'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_db',
    sa.Column('name', sa.String(length=64), nullable=False, comment='昵称'),
    sa.Column('account', sa.String(length=64), nullable=False, comment='账号'),
    sa.Column('password', sa.String(length=64), nullable=False, comment='密码'),
    sa.Column('brief', sa.String(length=64), nullable=False, comment='简介'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('note_db',
    sa.Column('title', sa.String(length=64), nullable=False, comment='笔记名'),
    sa.Column('content', sa.String(length=64), nullable=False, comment='笔记内容'),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['category_db.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_db',
    sa.Column('title', sa.String(length=128), nullable=False, comment='帖子标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='帖子内容'),
    sa.Column('draft', sa.Boolean(), nullable=True, comment='草稿'),
    sa.Column('cover', sa.String(length=32), nullable=False, comment='帖子封面路径'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['category_db.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_db.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_db',
    sa.Column('name', sa.String(length=64), nullable=False, comment='标签名'),
    sa.Column('color', sa.String(length=64), nullable=False, comment='标签颜色'),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['category_db.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment_db',
    sa.Column('name', sa.String(length=64), nullable=False, comment='附件名'),
    sa.Column('path', sa.String(length=64), nullable=False, comment='附件路径'),
    sa.Column('size', sa.Integer(), nullable=False, comment='附件大小'),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['note_id'], ['note_db.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post_db.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_db',
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('ip', sa.Integer(), nullable=False, comment='ip'),
    sa.Column('address', sa.String(length=64), nullable=False, comment='地址'),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['post_id'], ['post_db.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_note_association',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note_db.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_db.id'], )
    )
    op.create_table('tag_post_association',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_db.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_db.id'], )
    )
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False, comment='标题'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='内容'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tag_post_association')
    op.drop_table('tag_note_association')
    op.drop_table('comment_db')
    op.drop_table('attachment_db')
    op.drop_table('tag_db')
    op.drop_table('post_db')
    op.drop_table('note_db')
    op.drop_table('user_db')
    op.drop_table('message_db')
    op.drop_table('category_db')
    # ### end Alembic commands ###
