"""empty message

Revision ID: 6f3889b8b569
Revises: 2e9527d51acc
Create Date: 2024-11-13 23:41:38.149257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3889b8b569'
down_revision = '2e9527d51acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloginfo_ad',
    sa.Column('title', sa.String(length=64), nullable=False, comment='网站标题'),
    sa.Column('subtitle', sa.String(length=64), nullable=True, comment='网站副标题'),
    sa.Column('about_me', sa.Text(), nullable=True, comment='关于我'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ad',
    sa.Column('name', sa.String(length=64), nullable=False, comment='昵称'),
    sa.Column('account', sa.String(length=64), nullable=False, comment='账号'),
    sa.Column('password', sa.String(length=64), nullable=False, comment='密码'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('avatar_path', sa.String(length=256), nullable=True, comment='头像路径'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ad')
    op.drop_table('bloginfo_ad')
    # ### end Alembic commands ###
